language: csharp
solution: Plivo.sln

matrix:
  include:
    - dotnet: 2.0.0
      mono: none
      env: DOTNETCORE=2  # optional, can be used to take different code paths in your script
    - dotnet: 1.1.5 
      mono: none
      env: DOTNETCORE=1
    - mono: latest

install:
  - 'if [  ${DOTNETCORE} = 2 ]; then
        dotnet restore;
        dotnet build --framework netstandard2.0 src/Plivo/Plivo.csproj;
        dotnet build --framework netcoreapp2.0 tests_netcore/Plivo.NetCore.Test/Plivo.NetCore.Test.csproj;
    elseif [  ${DOTNETCORE} = 1 ]; then
        dotnet restore;
        dotnet build --framework netstandard1.3 src/Plivo/Plivo.csproj;
        dotnet build --framework netcoreapp1.1 tests_netcore/Plivo.NetCore.Test/Plivo.NetCore.Test.csproj;

        nuget restore Plivo.sln;
        nuget install NUnit.Runners -Version 3.9.0 -OutputDirectory testrunner;
    else 
        
    fi'

script:
  - dotnet test ./tests_netcore/Plivo.NetCore.Test/Plivo.NetCore.Test.csproj;
    
