language: csharp
solution: Plivo.sln

matrix:
  include:
    - dotnet: 1.1.5
      mono: none
      env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
    - mono: latest
      dotnet: 2.1.4

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

install:
  - 'if [  ${DOTNETCORE} = 1 ]; then
        dotnet restore;
        dotnet build --framework netstandard1.3 src/Plivo/Plivo.csproj;
        dotnet build --framework netcoreapp1.1 tests_netcore/Plivo.NetCore.Test/Plivo.NetCore.Test.csproj;
    else
        dotnet restore;
        nuget restore Plivo.sln;
        nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner;
    fi'

script:
  - 'if [  ${DOTNETCORE} = 1 ]; then
        dotnet test ./tests_netcore/Plivo.NetCore.Test/Plivo.NetCore.Test.csproj;
    else
        msbuild /p:Configuration=Release Plivo.sln;
        mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./tests/Plivo.Test/bin/Release/Plivo.Test.dll;
    fi'
