language: csharp
solution: Plivo.sln

matrix:
  include:
    - dotnet: 2.0.0
      mono: none
      env: DOTNETCORE=2  # optional, can be used to take different code paths in your script
    - dotnet: 1.3.0
      mono: none
      env: DOTNETCORE=1

install:
  - 'if [  ${DOTNETCORE} = 2 ]; then
        dotnet restore;
        dotnet build --framework netstandard2.0 src/Plivo/Plivo.csproj;
        dotnet build --framework netcoreapp2.0 tests_netcore/Plivo.NetCore.Test/Plivo.NetCore.Test.csproj;
    fi'
  - 'if [  ${DOTNETCORE} = 1 ]; then
        dotnet restore;
        dotnet build --framework netstandard1.3 src/Plivo/Plivo.csproj;
        dotnet build --framework netcoreapp1.1 tests_netcore/Plivo.NetCore.Test/Plivo.NetCore.Test.csproj;
    fi'

script:
  - 'if [  ${DOTNETCORE} = 2 ]; then
        dotnet test ./tests_netcore/Plivo.NetCore.Test/Plivo.NetCore.Test.csproj;
    fi'
  - 'if [  ${DOTNETCORE} = 1 ]; then
        dotnet test ./tests_netcore/Plivo.NetCore.Test/Plivo.NetCore.Test.csproj;
    fi'
